### ISSUE TITLE
About Prompts You Used

### ISSUE THREAD

**Issue by starrYYxuan** [OrangeInSouth/DeePEn#1]
Thanks for offering the code for this appealing work, may I ask for the prompts you used in the experiments? Thanks a lot!

**Comment by OrangeInSouth** [comment]
Hi, thanks for your attention!

The prompt is illustrated in the configuration files, such as: confs/ARC-c/baseline/InternLM.json

**Comment by starrYYxuan** [comment]
Thanks for the reply!
