### ISSUE TITLE
关于主模型和助理模型的合作问题。

### ISSUE THREAD

**Issue by shimurenhlq** [OrangeInSouth/DeePEn#3]
您的研究内容很有新意，我仔细阅读了论文并尝试运行代码，遇到了一个问题，如下所述。

我使用以下命令在NQ数据集上进行了测试：
export CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7
res_path=./res/NQ/LLaMA+Mistral
python ./src/main_many_ensemble_llama_series_local_matrix.py \
  --config confs/NQ/LLaMA+Mistral.json \
  -lpm based_on_probility_transfer_logits_fp32_processor \
  -d0 cuda:0 -d1 cuda:1 -dp cuda:2  \
  -rsd ${res_path} \
  -rm test -lr 0.15 -ew 0.5 0.5

虽然程序正常运行，但是会不断在命令行输出aux model0【not received】。

在程序运行结束后，我检查发现似乎对于每个问题，主模型和助理模型似乎仅在每个回答的第一个token进行了论文中所述的先在相对表示空间平均，再在主模型的绝对表示空间迭代搜索的过程。而后续的token都仅由主模型生成。

我另外运行了ARC数据集，其config文件中规定了max_new_token=1，因此不再显示aux model0【not received】。

请问是该方法本身就只在第一个生成的token上进行主模型与助理模型的集成，还是我在程序运行的过程中出现了什么错误？

论文中3.1节提到"At each decoding step, all models perform prediction and output N probability distributions."我的理解是每一个token都需要通过集成方法来生成，是我的理解出现了什么问题吗？

非常期待您的回复，谢谢！

**Comment by OrangeInSouth** [comment]
你好！抱歉因为一些事情耽误了回复。

你的理解没错，之前遇到的问题是由于我们上传的代码中存在bug导致的。

我们在最新的代码中修复了这个问题，非常感谢你的反馈！

**Comment by shimurenhlq** [comment]
谢谢您的回复！通过调整了“main_model_thread.join()”的位置解决了问题！
